#include <bits/stdc++.h>
using namespace std;


void solve(long long n, long long c, std::vector<long long> a){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long n;
    scanf("%lld",&n);
    long long c;
    scanf("%lld",&c);
    std::vector<long long> a(n);
    for(int i = 0 ; i < n ; i++){
        scanf("%lld",&a[i]);
    }
    solve(n, c, std::move(a));
    return 0;
}
