#!/usr/bin/env python3
import sys


def solve(N: int):
    ns = str(N)
    a = [0]*3
    for ni in ns:
        a[int(ni)%3]+=1

    rem = a[1]*1+a[2]*2

    if rem%3==0:
        print(0)
        return
    t = 0
    if rem%3 ==1:
        if a[1]>=1:
            a[1]-=1
            t=1
        elif a[2]>=2:
            a[2]-=2
            t=2
        
        if a[0]==a[1]==a[2]==0:
            print(-1)
        else:
            print(t)
        return
    elif rem%3 ==2:
        if a[2]>=1:
            a[2]-=1
            t=1
        elif a[1]>=2:
            a[1]-=2
            t=2
        
        if a[0]==a[1]==a[2]==0:
            print(-1)
        else:
            print(t)
        return


    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
