#!/usr/bin/env python3
import sys
import itertools as it

def solve(N: int, L: "List[int]"):
    a = 0
    L = sorted(L)
    for k in it.combinations(L,3):
        if (k[0] != k[1] != k[2]) and (k[0]+k[1]>k[2]):
            a+=1
    print(a)

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    L = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, L)

if __name__ == '__main__':
    main()
