#!/usr/bin/env python3

def make_divisors(n):
    divisors = []
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n//i)
    # divisors.sort()
    return divisors


def load_input():
    N = int(input())
    A = list(map(int, input().split(" ")))
    return N,A

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N,A = load_input()
    k = [0]*10000
    for ai in A:
        ds = make_divisors(ai)
        # print(ds)
        for di in ds:
            k[di]+=1
    k[1]=0

    print(k.index(max(k)))





if __name__ == '__main__':
    main()
