#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long start, long long goal, std::vector<long long> l, std::vector<long long> r){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long start;
    scanf("%lld",&start);
    long long goal;
    scanf("%lld",&goal);
    std::vector<long long> l(N-0+1);
    std::vector<long long> r(N-0+1);
    for(int i = 0 ; i < N-0+1 ; i++){
        scanf("%lld",&l[i]);
        scanf("%lld",&r[i]);
    }
    solve(N, start, goal, std::move(l), std::move(r));
    return 0;
}
