#!/usr/bin/env python3
import sys
import math


def solve(K: int):

    ans = 0
    for a in range(1,K+1):
        for b in range(a,K+1):
            for c in range(b,K+1):
                p=1
                if (a == b) or (b == c) or (a ==c):
                    p+=1
                    if (a==b==c):
                        p+=4
                ans += math.gcd(math.gcd(a,b),c)*(int(6/p))
                
    print(ans)

    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    solve(K)

if __name__ == '__main__':
    main()
