#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    i = input()
    if i.lower() == i:
        print("a")
    else:
        print("A")

    

if __name__ == '__main__':
    main()
