#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

void solve(long long N, long long M, long long K, std::vector<long long> D){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> D(N-1);
    for(int i = 0 ; i < N-1 ; i++){
        scanf("%lld",&D[i]);
    }
    solve(N, M, K, std::move(D));
    return 0;
}
