#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    c = list(input())

    nR = c.count("R")
    nW = c.count("W")
    rightR = c[nR:].count("R")
    leftW = c[:nR].count("W")
    print(max(rightR,leftW))

if __name__ == '__main__':
    main()
