#!/usr/bin/env python3
import numpy as np


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main(H,W,N,M,l,b):

    b = b*-2+1

    a = np.zeros((H,W))
    
    a[0]+=l[0]
    pre = l[0]
    for i in range(1,H):
        pre = (((pre*b[i]>0)*1 + l[i])>0)*1
        a[i] += pre
    
    a[H-1]+=l[H-1]
    pre = l[H-1]
    for i in range(H-2,-1,-1):
        pre = (((pre*b[i]>0)*1 + l[i])>0)*1
        a[i] += pre

    a = a.T
    l = l.T
    b = b.T

    a[0]+=l[0]
    pre = l[0]
    for i in range(1,W):
        pre = (((pre*b[i]>0)*1 + l[i])>0)*1
        a[i] += pre
    
    a[W-1]+=l[W-1]
    pre = l[W-1]
    for i in range(W-2,-1,-1):
        pre = (((pre*b[i]>0)*1 + l[i])>0)*1
        a[i] += pre

    print((a>0).sum())

    return



if __name__ == '__main__':
    H,W,N,M = map(int, input().split(" "))

    l = np.zeros((H,W))
    for i in range(N):
        ai,bi = map(int, input().split(" "))
        l[ai-1,bi-1] = 1

    b = np.zeros((H,W))
    for i in range(M):
        ci,di = map(int, input().split(" "))
        b[ci-1,di-1] = 1
    main(H,W,N,M,l,b)
