#include <bits/stdc++.h>
using namespace std;


void solve(std::vector<std::string> c){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::vector<std::string> c(8);
    for(int i = 0 ; i < 8 ; i++){
        std::cin >> c[i];
    }
    solve(std::move(c));
    return 0;
}
