#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> a, std::vector<long long> L, long long B){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> a(N);
    std::vector<long long> L(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&a[i]);
        scanf("%lld",&L[i]);
    }
    long long B;
    scanf("%lld",&B);
    solve(N, std::move(a), std::move(L), B);
    return 0;
}
