#!/usr/bin/env python3
import sys

# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]

    done = [int()]*(N)
    done_k = [0] * N


    i = 0
    q = 1
    while done_k[q-1] == 0:
        done[i] = q
        done_k[q-1] = 1
        i+=1
        q = A[q-1]
x
    f_q = done.index(q)
    r = i - f_q

    if K <= f_q:
        t = K
    else:
        k = (K - f_q)%r
        t = k + f_q

    print(done[t])        




if __name__ == '__main__':
    main()
