#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    H,W,X,Y = map(int, input().split(" "))
    m = [[_ for _ in input()] for _ in range(H)]

    ans = 0


    for i in range(X+1,H+1):
        if m[i-1][Y-1] == ".":ans+=1
        else:break
    # print(ans)
    for i in range(Y+1,W+1):
        if m[X-1][i-1] == ".":ans+=1
        else:break
    # print(ans)
    for i in range(X-1,0,-1):
        if m[i-1][Y-1] == ".":ans+=1
        else:break
    # print(ans)
    for i in range(Y-1,0,-1):
        if m[X-1][i-1] == ".":ans+=1
        else:break
    print(ans+1)

if __name__ == '__main__':
    main()
