#!/usr/bin/env python3


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    A = list(map(int, input().split(" ")))
    # print(N)
    # print(A)
    d_i = {}
    d_j = {}

    for i, ai in enumerate(A):
        p = ai -i
        if p in d_i.keys():
            d_i[p] +=1
        else:
            d_i[p] = 1
        p = -ai - i
        if p in d_j.keys():
            d_j[p] +=1
        else:
            d_j[p] = 1
    # print(d_i)
    # print(d_j)

    ans = 0
    for q in list(set(d_i.keys()) & set(d_j.keys())):
        ans += d_i[q]*d_j[q]
    print(ans)


    return


if __name__ == '__main__':
    main()
