#!/usr/bin/env python3
import sys
import math

def solve(a: int, b: int, x: int):
    full = a*a*b
    
    if x >= full//2:
        theta = math.atan(2*b/a-2*x/a/a/a)
    else:
        theta = math.atan(a*b*b/x/2)
    
    print(theta*180/math.pi)
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    a = int(next(tokens))  # type: int
    b = int(next(tokens))  # type: int
    x = int(next(tokens))  # type: int
    solve(a, b, x)

if __name__ == '__main__':
    main()
