#!/usr/bin/env python3
import sys


def solve(H: int, W: int, S: "List[str]"):
    a = 0
    print
    for y in range(H):
        for x in range(W-1):
            if S[y][x] == S[y][x+1] == ".":
                a+=1
    
    for x in range(W):
        for y in range(H-1):
            if S[y][x] == S[y+1][x] == ".":
                a+=1
    print(a)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, S)

if __name__ == '__main__':
    main()
